/*
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import ps.xtext.json.ide.contentassist.antlr.internal.InternalJSONParser;
import ps.xtext.json.services.JSONGrammarAccess;

public class JSONParser extends AbstractContentAssistParser {

	@Inject
	private JSONGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalJSONParser createParser() {
		InternalJSONParser result = new InternalJSONParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getBooleanAccess().getAlternatives(), "rule__Boolean__Alternatives");
					put(grammarAccess.getObjectAccess().getGroup(), "rule__Object__Group__0");
					put(grammarAccess.getObjectAccess().getGroup_2(), "rule__Object__Group_2__0");
					put(grammarAccess.getObjectAccess().getGroup_2_1(), "rule__Object__Group_2_1__0");
					put(grammarAccess.getPairAccess().getGroup(), "rule__Pair__Group__0");
					put(grammarAccess.getArrayAccess().getGroup(), "rule__Array__Group__0");
					put(grammarAccess.getArrayAccess().getGroup_2(), "rule__Array__Group_2__0");
					put(grammarAccess.getArrayAccess().getGroup_2_1(), "rule__Array__Group_2_1__0");
					put(grammarAccess.getNumberAccess().getGroup(), "rule__Number__Group__0");
					put(grammarAccess.getStrAccess().getGroup(), "rule__Str__Group__0");
					put(grammarAccess.getBooleanAccess().getGroup_0(), "rule__Boolean__Group_0__0");
					put(grammarAccess.getBooleanAccess().getGroup_1(), "rule__Boolean__Group_1__0");
					put(grammarAccess.getNullAccess().getGroup(), "rule__Null__Group__0");
					put(grammarAccess.getObjectAccess().getPairsAssignment_2_0(), "rule__Object__PairsAssignment_2_0");
					put(grammarAccess.getObjectAccess().getPairsAssignment_2_1_1(), "rule__Object__PairsAssignment_2_1_1");
					put(grammarAccess.getPairAccess().getStringAssignment_0(), "rule__Pair__StringAssignment_0");
					put(grammarAccess.getPairAccess().getValueAssignment_2(), "rule__Pair__ValueAssignment_2");
					put(grammarAccess.getArrayAccess().getValuesAssignment_2_0(), "rule__Array__ValuesAssignment_2_0");
					put(grammarAccess.getArrayAccess().getValuesAssignment_2_1_1(), "rule__Array__ValuesAssignment_2_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public JSONGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JSONGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
