/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import ps.xtext.json.ui.AbstractJSONUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class JSONUiModule extends AbstractJSONUiModule {
  public JSONUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
