/*
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJSONScopeProvider extends DelegatingScopeProvider {
}
