/*
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link JSONWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractJSONWebModule extends DefaultWebModule {

}
