/*
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import ps.xtext.json.ui.internal.JsonActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JSONExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JsonActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JsonActivator.getInstance().getInjector(JsonActivator.PS_XTEXT_JSON_JSON);
	}
	
}
