/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ps.xtext.json.JSONRuntimeModule;
import ps.xtext.json.JSONStandaloneSetup;
import ps.xtext.json.ide.JSONIdeModule;
import ps.xtext.json.web.JSONWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class JSONWebSetup extends JSONStandaloneSetup {
  @Override
  public Injector createInjector() {
    JSONRuntimeModule _jSONRuntimeModule = new JSONRuntimeModule();
    JSONIdeModule _jSONIdeModule = new JSONIdeModule();
    JSONWebModule _jSONWebModule = new JSONWebModule();
    return Guice.createInjector(Modules2.mixin(_jSONRuntimeModule, _jSONIdeModule, _jSONWebModule));
  }
}
