/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.web;

import ps.xtext.json.web.AbstractJSONWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class JSONWebModule extends AbstractJSONWebModule {
}
