/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>False</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ps.xtext.json.jSON.JSONPackage#getFalse()
 * @model
 * @generated
 */
public interface False extends ps.xtext.json.jSON.Boolean
{
} // False
