/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Null</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ps.xtext.json.jSON.JSONPackage#getNull()
 * @model
 * @generated
 */
public interface Null extends Value
{
} // Null
