/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ps.xtext.json.jSON.Object#getPairs <em>Pairs</em>}</li>
 * </ul>
 *
 * @see ps.xtext.json.jSON.JSONPackage#getObject()
 * @model
 * @generated
 */
public interface Object extends Value
{
  /**
   * Returns the value of the '<em><b>Pairs</b></em>' containment reference list.
   * The list contents are of type {@link ps.xtext.json.jSON.Pair}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pairs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pairs</em>' containment reference list.
   * @see ps.xtext.json.jSON.JSONPackage#getObject_Pairs()
   * @model containment="true"
   * @generated
   */
  EList<Pair> getPairs();

} // Object
