/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Str</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ps.xtext.json.jSON.JSONPackage#getStr()
 * @model
 * @generated
 */
public interface Str extends Value
{
} // Str
