/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>True</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ps.xtext.json.jSON.JSONPackage#getTrue()
 * @model
 * @generated
 */
public interface True extends ps.xtext.json.jSON.Boolean
{
} // True
