/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ps.xtext.json.jSON.JSONPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
} // Value
