/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.ui.contentassist;

import ps.xtext.json.ui.contentassist.AbstractJSONProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class JSONProposalProvider extends AbstractJSONProposalProvider {
}
