/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.validation;

import ps.xtext.json.validation.AbstractJSONValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JSONValidator extends AbstractJSONValidator {
}
