/*
 * generated by Xtext 2.12.0
 */
package ps.xtext.json


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JSONStandaloneSetup extends JSONStandaloneSetupGenerated {

	def static void doSetup() {
		new JSONStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
