/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json;

import ps.xtext.json.AbstractJSONRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JSONRuntimeModule extends AbstractJSONRuntimeModule {
}
