/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json;

import ps.xtext.json.JSONStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class JSONStandaloneSetup extends JSONStandaloneSetupGenerated {
  public static void doSetup() {
    new JSONStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
