/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import ps.xtext.json.JSONRuntimeModule;
import ps.xtext.json.JSONStandaloneSetup;
import ps.xtext.json.ide.JSONIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class JSONIdeSetup extends JSONStandaloneSetup {
  @Override
  public Injector createInjector() {
    JSONRuntimeModule _jSONRuntimeModule = new JSONRuntimeModule();
    JSONIdeModule _jSONIdeModule = new JSONIdeModule();
    return Guice.createInjector(Modules2.mixin(_jSONRuntimeModule, _jSONIdeModule));
  }
}
