/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.ide;

import ps.xtext.json.ide.AbstractJSONIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class JSONIdeModule extends AbstractJSONIdeModule {
}
