/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON.impl;

import org.eclipse.emf.ecore.EClass;

import ps.xtext.json.jSON.JSONPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BooleanImpl extends ValueImpl implements ps.xtext.json.jSON.Boolean
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BooleanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JSONPackage.Literals.BOOLEAN;
  }

} //BooleanImpl
