/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON.impl;

import org.eclipse.emf.ecore.EClass;

import ps.xtext.json.jSON.JSONPackage;
import ps.xtext.json.jSON.Str;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Str</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StrImpl extends ValueImpl implements Str
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StrImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JSONPackage.Literals.STR;
  }

} //StrImpl
