/**
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.jSON.impl;

import org.eclipse.emf.ecore.EClass;

import ps.xtext.json.jSON.JSONPackage;
import ps.xtext.json.jSON.True;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>True</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TrueImpl extends BooleanImpl implements True
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TrueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JSONPackage.Literals.TRUE;
  }

} //TrueImpl
