/*
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JSONAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ps/xtext/json/parser/antlr/internal/InternalJSON.tokens");
	}
}
