/*
 * generated by Xtext 2.12.0
 */
package ps.xtext.json.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import ps.xtext.json.ui.internal.JsonActivator;

public class JSONUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JsonActivator.getInstance().getInjector("ps.xtext.json.JSON");
	}

}
